---
- hosts: rocky
  become: true

  vars:
   app_dir: /usr/local/opt/node/book-lookup-app

  tasks:
   - name: Install node.js dependencies
     command:
      chdir: "{{ app_dir }}"
      cmd: npm install

   - name: Build app
     chdir: "{{ app_dir }}"
     cmd: npm run build

   - name: Install serve
     chdir: "{{ app_dir }}"
     cmd: npm install serve

   - name: Start express
     chdir: /usr/local/opt/node/book-lookup-app/build
     cmd: serve -p 80
