---
- hosts: rocky
  become: true

  tasks:
   - name: Install node.js dependencies
     command:
      chdir: /usr/local/opt/node/book-lookup-app
      cmd: |
       npm install
       npm run build
       npm install serve

   - name: Start express
     chdir: /usr/local/opt/node/book-lookup-app/build serve -p 80
