---
- hosts: rocky
  become: true

  vars:
   app_dir: /usr/local/opt/node/book-lookup-app

  tasks:
   - name: Install node.js dependencies
     ansible.builtin.command:
      chdir: "{{ app_dir }}"
      cmd: |
       npm install
       npm run deploy
     changed_when: false

  #  - name: Start app
  #    ansible.builtin.command:
  #     chdir: "{{ app_dir }}"
  #     cmd: npm start
  #    changed_when: false

  #  - name: Build app
  #    ansible.builtin.command:
  #     chdir: "{{ app_dir }}"
  #     cmd: npm run build
  #    changed_when: false

  #  - name: Install serve
  #    ansible.builtin.command:
  #     chdir: "{{ app_dir }}"
  #     cmd: npm install serve
  #    changed_when: false


  #  - name: Start express
  #    ansible.builtin.command:
  #     chdir: /usr/local/opt/node/book-lookup-app/build
  #     cmd: serve -p 80
  #    changed_when: false
