---
- hosts: rocky
  become: true
# Repurpose this playbook for app
  vars:
   node_apps_location: /usr/local/opt/node

  pre_tasks: []

  roles:
   - nodejs
#  nodejs role used to setup node.js for our app

  tasks:
   - name: Ensure Node.js app folder exists.
     file:
      path: "{{ node_apps_location }}"
      state: directory

  #  - include_role: nodejs - using this allows us to call a role anywhere in our tasks list

   - name: Copy example Node.js app to server
     copy:
      src: "/var/lib/jenkins/workspace/Test_Pipeline/app/book-lookup-app"
      dest: "{{ node_apps_location }}"
     changed_when: false

   - name: Install app dependencies defined in package.json
     npm:
      path: "{{ node_apps_location }}/book-lookup-app"

   - name: Check list of running Node.js apps.
     command: /usr/local/bin/forever list
     register: forever_list
     changed_when: false

   - name: Start example Node.js apps.
     command: "/usr/local/bin/forever start {{ node_apps_location }}/app/src/book-lookup-app/src/App.js"
     when: "forever_list.stdout.find(node_apps_location + '/app/src/book-lookup-app/src/App.js') == -1"