---
- hosts: localhost
  connection: local
  become_user: admin
  gather_facts: false

  tasks:
  - name: Get date of jenkins server
    command: date
    register: date

  - name: Display date
    debug:
     msg: "{{ date.stdout }}"
